### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by SaFrMo** [SaFrMo/THREE.extendMaterial#1]
- [x] Produce full copy of material in ShaderMaterial
- [x] Allow shader customization
- [x] Allow uniform customization
